config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :repositories, only: :pull do
      member do
        post :pull
      end
    end

    resources :containers, only: [:create, :destroy]
  end

  resources :images
end

app/models/container.rb
# == Schema Information
#
# Table name: containers
#
#  id                  :integer          not null, primary key
#  image_id            :string
#  docker_container_id :string
#  name                :string
#  branch_name         :string
#  project_id          :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Container < ActiveRecord::Base
  belongs_to :project
  has_one :repository, through: :project

  after_commit   :setup_container, on: :create
  before_destroy :destroy_container, :if => proc { ready? }
  before_destroy :delete_slug

  def ready?
    !!docker_container_id
  end

  def docker_container
    return nil unless ready?
    @docker_container ||= Docker::Container.get docker_container_id
  end

  def name
    info['Name']
  end

  def ip
    info['NetworkSettings']['IPAddress']
  end

  def ports
    info['NetworkSettings']['Ports']
  end

  def urls
    return [] unless ports
    ports.map { |port| "http://#{ip.to_s}:#{port.join[/\d+/]}" }
  end

  def info
    ready? ? docker_container.info : {}
  end

  def slug_name
    "#{project.name}_#{id}.tgz"
  end

  def slug_path
    @slug_path ||= [ slug_dir, slug_name ].join '/'
  end

  def slug_dir
    [ Cointegrator::Application.config.slugs_path, id ].join '/'
  end

  private
    def destroy_container
      Containers::DestroyerJob.perform_later self
    end

    def delete_slug
      FileUtils.rm_rf slug_dir
    end

    def setup_container
      Containers::SlugBuilderJob.perform_later self
    end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id             :integer          not null, primary key
#  name           :string
#  description    :text
#  docker_options :string
#  repository_id  :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Project < ActiveRecord::Base
  has_one  :repository, dependent: :destroy
  has_many :containers, dependent: :destroy
  accepts_nested_attributes_for :repository
end

app/models/repository.rb
# == Schema Information
#
# Table name: repositories
#
#  id         :integer          not null, primary key
#  project_id :integer
#  remote_url :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Repository < ActiveRecord::Base
  after_commit   :clone_async, on: :create
  before_destroy :remove_repo

  belongs_to :project

  def clone  
    Rugged::Repository.clone_at(remote_url, local_path)
  end

  def local_path
    @local_path ||= [ Cointegrator::Application.config.repos_path, id.to_s, project.name ].join '/'
  end

  def cloned?
    Pathname.new(local_path + '/.git/HEAD').exist?
  end

  def clone_async
    Git::ClonerJob.perform_later self
  end

  def git
    return nil unless cloned?
    @git ||= Rugged::Repository.new(local_path)
  end

  def pull
    git.remotes.each { |remote| remote.fetch }
  end

  private
    def remove_repo
      FileUtils.rm_rf(local_path)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  before_action :set_container, except: [:create]

  def create
    @container = Container.new container_params

    if @container.save
      flash[:notice] = 'Container created'
    end
    redirect_to project_path(params[:project_id])
  end

  def destroy
    if @container.destroy
      flash[:notice] = 'Container destroyed'
    end
    redirect_to project_path(params[:project_id])
  end

  private
    def set_container
      @container = Container.find(params[:id])
    end

    def container_params
      params.require(:container).permit(:branch_name).merge(project_id: params[:project_id])
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, except: :index

  def show
  end

  def index
    @images = Docker::Image.all
  end

  def destroy
    if @image.remove(force: true)
      flash[:notice] = 'Image removed'
    end
    redirect_to images_path
  end

  private
  def set_image
    @image = Docker::Image.get params[:id]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, except: [:index, :create, :new]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
    @project.build_repository
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    puts @project.inspect

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_project
      @project = Project.find(params[:id])
    end


    def project_params
      params.require(:project).permit(:name, :description, :docker_options, repository_attributes: [:remote_url])
    end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_project
  def create
    if @project.create_repository repository_params
      flash[:notice] = 'Application cloned'
    end
    redirect_to @project
  end

  def pull
    @project.repository.pull
    flash[:notice] = 'Repository updated'
    redirect_to @project
  end

  private
    def set_project
      @project = Project.find params[:project_id]
    end

    def repository_params
      params.permit(:repository).require(:remote_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def glyphicon(name, text: nil, before_text: nil)
    "#{before_text} <span class=\"glyphicon #{name}\"></span> #{text}".html_safe
  end
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/images/index.html.haml
%h3 Docker images:
%ol
  - @images.each do |image|
    %li
      = link_to image.id, image_path(image)
      %dl
        %dt Created
        %dd= image.info['Created']
        %dt Tags
        %dd
          [#{image.info['RepoTags'].join ', '}]
      = link_to 'Destroy', image_path(image), method: :delete, class: 'btn btn-xs btn-danger'

app/views/images/show.html.haml
%h2= @image.id
%dl
  - @image.info.each_pair do |key, value|
    - unless value.is_a?(String) && value.empty?
      %dt= key
      %dd= value

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  - if key == :notice
    - alert_type = 'alert-success'
  - elsif key == :warn || key == :warning
    - alert_type = 'alert-warning'
  - elsif key == :error || key == :alert
    - alert_type = 'alert-danger'
  - else
    - alert_type = 'alert-info'
  %div{:class => "alert #{alert_type} alert-dismissable"}
    = value

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-brand Cointegrator
    .navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li
          = link_to 'Images', images_path
        %li
          = link_to 'Projects', projects_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Cointegrator
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      = render 'layouts/flash'
      = yield

app/views/projects/_form.html.haml
= form_for(@project) do |f|
  - if @project.errors.any?
    #error_explanation
      %h2
        = pluralize(@project.errors.count, "error")
        prohibited this project from being saved:
      %ul
        - @project.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .field
    = f.label :docker_options
    %br/
    = f.text_field :docker_options
  = f.fields_for :repository do |repo_fields|
    .field
      = repo_fields.label :remote_url
      %br/
      = repo_fields.text_field :remote_url
  .actions
    = f.submit

app/views/projects/edit.html.haml
%h1 Editing Project
= render 'form'
= link_to 'Show', @project
|
\#{link_to 'Back', projects_path}

app/views/projects/index.html.haml
%p#notice= notice
%h1 Listing Projects
%table
  %thead
    %tr
      %th Name
      %th Description
      %th Repo url
      %th Docker options
      %th{:colspan => "3"}
  %tbody
    - @projects.each do |project|
      %tr
        %td= project.name
        %td= project.description
        %td= project.docker_options
        %td= link_to 'Show', project
        %td= link_to 'Edit', edit_project_path(project)
        %td= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1 New Project
= render 'form'
= link_to 'Back', projects_path

app/views/projects/show.html.haml
%h2= @project.name
%p
  %strong Description:
  = @project.description
%p
  %strong Repo url:
  = @project.repository.remote_url
%p
  %strong Docker options:
  = @project.docker_options

- if @project.repository && @project.repository.cloned?
  %p
    %strong Last commit:
    = @project.repository.git.head.target.message
    %i= @project.repository.git.head.target_id
  = link_to glyphicon('glyphicon-refresh', before_text: 'Refresh repository'), pull_project_repository_path(@project, @project.repository.id), class: 'btn btn-default', method: :post
  %div
  %h3 Branches
  %ul
    - @project.repository.git.branches.each_name(:remote).sort.each do |branch_name|
      %li
        = branch_name
        = link_to 'Run', project_containers_path(@project, container: { branch_name: branch_name }), class: 'btn btn-success btn-xs', method: :post
- else
  %p We are cloning your repository. That can take few seconds.
  .progress
    .progress-bar.progress-bar-info.progress-bar-striped.active{:role => "progressbar", :style => "width: 100%"}   

- if @project.containers.any?
  %div
    %h3 Containers
    - @project.containers.each do |container|
      .panel.panel-default
        .panel-heading
          = container.name
          &nbsp;
          .pull-right
            = button_to 'Destroy', project_container_path(@project, container), method: :delete, class: 'btn btn-danger btn-xs'
        .panel-body
          - if container.ready?
            - container.urls.each do |url|
              %p= link_to url, url, target: '_blank'
            %dl
              %dt Image ID
              %dd= container.image_id
          - else
            %p Please wait. We are building a container for your app. That can take few minutes.
            .progress
              .progress-bar.progress-bar-info.progress-bar-striped.active{:role => "progressbar", :style => "width: 100%"}        
          %dl
            %dt Branch
            %dd= container.branch_name

= link_to 'Edit', edit_project_path(@project)
= link_to 'Back', projects_path